### PR TITLE
[READY] More idiomatic imports in `__init__` files

### PR DESCRIPTION
**Pull request by PABannier**
This PR changes the imports in the `__init__` files of the Datafit and Penalty submodules.
As suggested by @mathurinm , instead of appending `noqa F401` at the end of every line, imported objects can be made available in `__all__`.

### CODE REVIEW

**Review by Badr-MOUFAD — COMMENTED** [review]
@PABannier, looks tempting! Yet, I think by doing so, we introduce some redundancy as we should always keep the ``__all__`` synchronized with the imports.

I am not really in favor of this change. IMO, So far the ``#noqa`` doesn't hurt us much.

**Comment by PABannier** [comment]
@mathurinm WDYT? I opened the PR to make it consistent with the changes made in #63 for the `solver` submodule.

**Comment by QB3** [comment]
It is true that we are currently introducing it in the `solver` PR https://github.com/mathurinm/skglm/blob/0cee34a3b8d7631406ba5158f30d6a66f16ab0a3/skglm/solvers/__init__.py#L9

> Yet, I think by doing so, we introduce some redundancy as we should always keep the __all__ synchronized with the imports.

I am not sure to understand what you mean here, what is the potential problem?

**Comment by PABannier** [comment]
So if we all agree that the maintenance cost (to keep the imports and `__all__` synchronized) is minimal, can we merge the PR? I need 2 approvals.

**Review by Badr-MOUFAD — APPROVED** [review]

**Comment by mathurinm** [comment]
Thanks PA!

**Pull request merged**
